server:
  port: 8090
  context-path: /uad
  jsp-servlet:
    init-parameters:
      development: true
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cmfz
    username: root
    password: root
  mvc:
    view:
      prefix: /
      suffix: .jsp
  http:
    multipart:
      max-file-size: 20480000
      max-request-size: 204800000000
mybatis:
  mapper-locations: classpath:/com/baizhi/mapper/*Mapper.xml
  type-aliases-package: com.baizhi.entity